language:
    - c
compiler:
    - gcc
before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -y lv2core liblilv-dev lilv-utils
    - git clone https://github.com/portalmod/lv2bm
    - cd lv2bm && make && make install
script:
    - make
    - INSTALL_PATH=~/.lv2 make install
    - lv2bm --full-test `lv2ls | grep tap`
